spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
    username: 'root'
    password: '1'
  application:
    name: BaseApplication
management:
  tracing:
    sampling:
      probability: 1.0
dubbo:
  application:
    name: BaseApplication
  config-center:
    namespace: dev
    address: nacos://${nacos.address:127.0.0.1}:8848
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.wh.dubbbo.demo.base.entity
